### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by frameswolfe**
and seeded 40 real UK venues

### CODE REVIEW

**Comment by SimonBao** [comment]
Looks good, but atm it scrolls since the vh is set to 100.

**Comment by SimonBao** [comment]
> Looks good, but atm it scrolls since the vh is set to 100.

I think we spoke about this yesterday and you mentioned it'll be good not having scroll on the website.

**Comment by frameswolfe** [comment]
so I'm hoping we can set the navbar to sticky to get around the scrolling issue. Agree we don't want the homepage (or any page?) to scroll

**Comment by SimonBao** [comment]
Since other pages have been designed with the navbar taking up height, I think it's better to just change the vh on the homepage so it wont effect the other pages. And why do we want a sticky navbar if there's no scrolling?

**Comment by frameswolfe** [comment]
yeah maybe sticky's not the right word but i just meant like an overlay. Isn't it just the default navbar atm though or have you been designing based around it as it is?

**Comment by frameswolfe** [comment]
Ben's suggesting to sack the navbar on the homepage

**Comment by SimonBao** [comment]
Pretty much as is, since it's not too far off our figma height.

But give the sticky/overlay a go, it might be fine 👍

**Pull request merged**
