### PR TITLE
Tours show

### PR DESCRIPTION
**Pull request by frameswolfe**

### CODE REVIEW

**Comment by SimonBao** [comment]
The rest if fine apart from the universal selector thing

**Comment by frameswolfe** [comment]
y u hatin?

**Comment by SimonBao** [comment]
can't be a hater nah?

**Comment by frameswolfe** [comment]
alright it's gone

**Comment by SimonBao** [comment]
cool, that thing is the reason why the text became invisible on venue show too

**Comment by frameswolfe** [comment]
yeah I know, i was gonna fix that next!

**Comment by frameswolfe** [comment]
i'll sort the backgrounds first and add it back later ;)

**Pull request merged**
